apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: k8s-app:v10
        ports:
        - containerPort: 4000
      - name: kubectl-proxy
        image: lachlanevenson/k8s-kubectl:v1.6.4
        args: ["proxy"]